{% set name = "sagemaker_inference" %}
{% set version = "1.3.2" %}

package:
  name: sagemaker-inference-toolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6a41cad2f8e0a1463167bfe7110845bdfc7156896002b779eafd9dd5bb7ca63

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - python
    - six
    - typing

test:
  imports:
    - sagemaker_inference

about:
  home: https://github.com/aws/sagemaker-inference-toolkit/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source toolkit for helping create serving containers to run on Amazon SageMaker.
  doc_url: https://pypi.org/project/sagemaker-inference/
  dev_url: https://github.com/aws/sagemaker-inference-toolkit/

extra:
  recipe-maintainers:
    - mwilson8
    - rluria14
    - benhuff
